//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C_EgitimKamp_301.EfProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Guide
    {
        public Guide()
        {
            this.Location = new HashSet<Location>();
        }
    
        public int GuideId { get; set; }
        public string GuideName { get; set; }
        public string GuideSurname { get; set; }
    
        public virtual ICollection<Location> Location { get; set; }
    }
}
