//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C_EgitimKamp_301.EfProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EğitimKampıEFTravelDbEntities2 : DbContext
    {
        public EğitimKampıEFTravelDbEntities2()
            : base("name=EğitimKampıEFTravelDbEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin> Admin { get; set; }
        public DbSet<Customer> Customer { get; set; }
        public DbSet<Guide> Guide { get; set; }
        public DbSet<Location> Location { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
